tests_include:
  - check_ospf_leaf1
  - check_ospf_leaf2
  - check_ospf_leaf3
  - check_ospf_leaf4

### ---------------------------------------------------------------------------------
### Ensure All ISIS adjacencies are UP 
### ---------------------------------------------------------------------------------
check_ospf_leaf1:
  - rpc: get-ospf-neighbor-information

  - iterate:
      xpath: '//ospf-neighbor-information/ospf-neighbor[normalize-space(interface-name) = "xe-0/0/1.0"]'
      tests:
        - is-equal: ospf-neighbor-state, Full
          err: OSPF Neighbor {{post['ospf-neighbor-state']}} is not Full on xe-0/0/1.0 (Full expected)

check_ospf_leaf2:
  - rpc: get-ospf-neighbor-information

  - iterate:
      xpath: '//ospf-neighbor-information/ospf-neighbor[normalize-space(interface-name) = "xe-0/0/2.0"]'
      tests:
        - is-equal: ospf-neighbor-state, Full
          err: OSPF Neighbor {{post['ospf-neighbor-state']}} is not Full on xe-0/0/2.0 (Full expected)

check_ospf_leaf3:
  - rpc: get-ospf-neighbor-information

  - iterate:
      xpath: '//ospf-neighbor-information/ospf-neighbor[normalize-space(interface-name) = "xe-0/0/3.0"]'
      tests:
        - is-equal: ospf-neighbor-state, Full
          err: OSPF Neighbor {{post['ospf-neighbor-state']}} is not Full on xe-0/0/3.0 (Full expected)

check_ospf_leaf4:
  - rpc: get-ospf-neighbor-information

  - iterate:
      xpath: '//ospf-neighbor-information/ospf-neighbor[normalize-space(interface-name) = "xe-0/0/4.0"]'
      tests:
        - is-equal: ospf-neighbor-state, Full
          err: OSPF Neighbor {{post['ospf-neighbor-state']}} is not Full on xe-0/0/4.0 (Full expected)

