### ---------------------------------------------------------------------------
### RETRIEVE BGP EVPN ROUTE TABLE FROM DEVICE
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  become: False
  roles: 
    - juniper.junos
  vars:
    provider_info:
      user: automation
      passwd: juniper123
  tasks:
    - name: "### RETRIEVE BGP EVPN ROUTE TABLE WITH NETCONF ###"
      juniper_junos_rpc:
        host: "{{ ansible_host }}"
        user: "{{ provider_info.user }}"
        passwd: "{{ provider_info.passwd }}"
        rpc: get_route_information
        kwargs:
          table: iso.0
          extensive: True
      register: output_route_table

    - name: "### PRINT THE RESULT TO CONSOLE ###"
      debug:
        msg: "{{ output_route_table.parsed_output }}"
      when: output_route_table is defined
