### ---------------------------------------------------------------------------
### RETRIEVE LLDP NEIGHBORS FROM DEVICE
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  become: False
  roles: 
    - juniper.junos
  vars:
    provider_info:
      host: "{{ inventory_hostname }}"
      user: "ansible"
      passwd: "hol-leap!bru6PSOO"
      # ssh_private_key_file: "~/.ssh/ansible"
  tasks:
    - name: "### RETRIEVE LLDP NEIGHBORS WITH NETCONF ###"
      juniper_junos_rpc:
        host: "{{ ansible_host }}"
        user: "{{ provider_info.user }}"
        passwd: "{{ provider_info.passwd }}"
        rpc: get-lldp-neighbors-information
      register: output_lldp_neighbors

    - name: "### PRINT THE RESULT TO CONSOLE ###"
      debug:
        msg: "{{ output_lldp_neighbors.parsed_output }}"
      when: output_lldp_neighbors is defined
