tests_include:
  - check_isis_leaf1
  - check_isis_leaf2
  - check_isis_leaf3
  - check_isis_leaf4


### ---------------------------------------------------------------------------------
### Ensure All ISIS adjacencies are UP 
### ---------------------------------------------------------------------------------
check_isis_leaf1:
  - rpc: get-isis-adjacency-information

  - iterate:
      xpath: '//isis-adjacency-information/isis-adjacency[normalize-space(interface-name) = "xe-0/0/1.0"]'
      tests:
        - is-equal: system-name, pod1-leaf1
          err: ISIS Neighbor {{post['system-name']}} is found on interface xe-0/0/1.0 (pod1-leaf1 expected)

check_isis_leaf2:
  - rpc: get-isis-adjacency-information

  - iterate:
      xpath: '//isis-adjacency-information/isis-adjacency[normalize-space(interface-name) = "xe-0/0/2.0"]'
      tests:
        - is-equal: system-name, pod1-leaf2
          err: ISIS Neighbor {{post['system-name']}} is found on interface xe-0/0/2.0 (pod1-leaf2 expected)

check_isis_leaf3:
  - rpc: get-isis-adjacency-information

  - iterate:
      xpath: '//isis-adjacency-information/isis-adjacency[normalize-space(interface-name) = "xe-0/0/3.0"]'
      tests:
        - is-equal: system-name, pod1-leaf3
          err: ISIS Neighbor {{post['system-name']}} is found on interface xe-0/0/3.0 (pod1-leaf3 expected)

check_isis_leaf4:
  - rpc: get-isis-adjacency-information

  - iterate:
      xpath: '//isis-adjacency-information/isis-adjacency[normalize-space(interface-name) = "xe-0/0/4.0"]'
      tests:
        - is-equal: system-name, pod1-leaf4
          err: ISIS Neighbor {{post['system-name']}} is found on interface xe-0/0/4.0 (pod1-leaf4 expected)

